//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.11.14 at 08:53:54 PM MSK 
//


package com.geekbrain.market.soap;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.geekbrains.market.soap package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.geekbrains.market.soap
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetProductSOAPRequest }
     * 
     */
    public GetProductSOAPRequest createGetProductSOAPRequest() {
        return new GetProductSOAPRequest();
    }

    /**
     * Create an instance of {@link GetAllProductSOAPRequest }
     * 
     */
    public GetAllProductSOAPRequest createGetAllProductSOAPRequest() {
        return new GetAllProductSOAPRequest();
    }

    /**
     * Create an instance of {@link GetProductSOAPResponse }
     * 
     */
    public GetProductSOAPResponse createGetProductSOAPResponse() {
        return new GetProductSOAPResponse();
    }

    /**
     * Create an instance of {@link ProductSOAP }
     * 
     */
    public ProductSOAP createProductSOAP() {
        return new ProductSOAP();
    }

    /**
     * Create an instance of {@link GetAllProductSOAPResponse }
     * 
     */
    public GetAllProductSOAPResponse createGetAllProductSOAPResponse() {
        return new GetAllProductSOAPResponse();
    }

}
